[package]
name = "register-selftest-generator-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = { workspace = true }
thiserror = "1.0.38"
log = "0.4.17"
