build:
    SVD_PATH=$(readlink -f headsail-sysctrl-v0.1.1.svd) ARCH_PTR_BYTES=4 INCLUDE_SYMS_REGEX="^HPC" cargo +nightly build --release
run:
    SVD_PATH=$(readlink -f headsail-sysctrl-v0.1.1.svd) ARCH_PTR_BYTES=4 INCLUDE_SYMS_REGEX="^HPC" cargo +nightly run --release
