[workspace]
members = [
    "register-selftest-generator-common",
    "register-selftest-generator-parse",
    "register-selftest-facade",
    "register-selftest-generator-runner",
]

[workspace.dependencies]
json = "0.12"
