name: Build & lint keelhaul

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: 1
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update toolchain
      run: |
        rustup update
        rustup component add clippy
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

  check-keelhaul:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Lint
      working-directory: ./keelhaul
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings
    - name: Test
      working-directory: ./keelhaul
      run: |
        cargo check
        cargo test --all
    - name: Build
      working-directory: ./keelhaul
      run: cargo build --release

  check-keelhaul-cli:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Lint
      working-directory: ./keelhaul-cli
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings
    - name: Test
      working-directory: ./keelhaul-cli
      run: |
        cargo check
        cargo test --all
    - name: Build
      working-directory: ./keelhaul-cli
      run: cargo build --release
